name: v4 auto database update
on:
  schedule:
    - cron: '18 23 * * Tue,Fri'
  workflow_dispatch:
jobs:
  release:
    name: v4 version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - name: install dependencies
        run: npm i
      - name: update
        run: npm run updatedb
        env:
          GEOLITE2_LICENSE_KEY: ${{secrets.GEOLITE2_LICENSE_KEY}}
      - name: update-package
        run: npm run update-package
      - name: test
        run: npm run test
      - name: commit
        run: scripts/release.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GTOKEN}}
          branch: v4
      - name: release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
